- hosts: web* 
  remote_user: ubuntu 

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install Packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    become: yes
    vars:
      packages:
      - tmux # tmux is a need
      - build-essential
      - git
      - vim
      - aptitude
      - certbot
      - python3-certbot-dns-route53

  - name: Create .aws directory
    file:
      path: /home/ubuntu/.aws
      state: directory

  - name: Create config directory
    file:
      path: "{{ dirs }}"
      state: directory
    vars:
      dirs:
        - /home/ubuntu/letsencrypt/config
        - /home/ubuntu/letsencrypt/log
        - /home/ubuntu/letsencrypt/work

  - name: Add AWS CLI credentials
    copy:
      dest: "/home/ubuntu/.aws/credentials"
      content: |
        [default]
        aws_access_key_id = {{ key_id }}
        aws_secret_access_key = {{ key_secret }}

  - name: Add AWS CLI config
    copy:
      dest: "/home/ubuntu/.aws/config"
      content: |
        [default]
        region = ap-southeast-2
  
  - name: Get TLS certificate
    shell: certbot certonly -d *.mycsronline.com --dns-route53 -m {{ email }} --agree-tos -n --logs-dir /home/ubuntu/letsencrypt/log --work-dir /home/ubuntu/letsencrypt/work --config-dir /home/ubuntu/letsencrypt/config
    args:
      executable: /bin/bash

