- hosts: {{ domain }} 
  remote_user: ubuntu 

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install Packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    become: yes
    vars:
      packages:
      - tmux # tmux is a need
      - build-essential
      - git
      - vim
      - aptitude
      - certbot
      - python3-certbot-dns-route53
      - jq

  - name: Create .aws directory
    file:
      path: /home/ubuntu/.aws
      state: directory

  - name: Create config directory
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "/home/ubuntu/letsencrypt/config"
      - "/home/ubuntu/letsencrypt/log"
      - "/home/ubuntu/letsencrypt/work"
      - "/home/ubuntu/modlishka/"

  - name: Add AWS CLI credentials
    copy:
      dest: "/home/ubuntu/.aws/credentials"
      content: |
        [default]
        aws_access_key_id = {{ key_id }}
        aws_secret_access_key = {{ key_secret }}

  - name: Add AWS CLI config
    copy:
      dest: "/home/ubuntu/.aws/config"
      content: |
        [default]
        region = ap-southeast-2
  
  - name: Get TLS certificate
    shell: certbot certonly -d "*.web.{{ domain }}" --dns-route53 -m {{ email }} --agree-tos -n --logs-dir "/home/ubuntu/letsencrypt/log" --work-dir "/home/ubuntu/letsencrypt/work" --config-dir "/home/ubuntu/letsencrypt/config"
    args:
      executable: /bin/bash

  - name: Download modlishka
    get_url:
      url: https://github.com/drk1wi/Modlishka/releases/download/v.1.1.0/Modlishka-linux-amd64 
      dest: /usr/local/bin/modlishka
      mode: 0755
    become: yes

  - name: Download example google config
    get_url:
      url: https://raw.githubusercontent.com/drk1wi/Modlishka/master/templates/google.com_gsuite.json
      dest: /home/ubuntu/modlishka/google.com.json

  - name: Download example office config
    get_url:
      url: https://raw.githubusercontent.com/drk1wi/Modlishka/master/templates/office365.json
      dest: /home/ubuntu/modlishka/office365.json

  - name: Create JSON friendly private key
    shell: awk '{printf "%s\\n", $0}' letsencrypt/config/live/web.{{ domain }}/privkey.pem > privkey.txt
    args:
      executable: /bin/bash

  - name: Create JSON friendly cert
    shell: awk '{printf "%s\\n", $0}' letsencrypt/config/live/web.{{ domain }}/fullchain.pem > fullchain.txt
    args:
      executable: /bin/bash

  - name: Use jq to add cert and key to json template
    shell: cat modlishka/office365.json | jq ".cert=\"$(cat fullchain.txt)\"" | jq ".certKey=\"$(cat privkey.txt)\"" | jq ".proxyDomain=\"web.{{ domain }}\"" > modlishka/template.json
    args:
      executable: /bin/bash

  - name: Remove aws config
    file: 
      state: absent
      path: /home/ubuntu/.aws
